### ISSUE TITLE
Doesn't "build" on Windows

### ISSUE THREAD

**Issue by wildeyes** [VeliovGroup/Meteor-Template-helpers#2]
"$ meteor add ostrio:templatehelpers  
 => Errors while adding packages:                                                                                                                      

While building package ostrio:templatehelpers:  
error: Couldn't build this package on Windows due to the following file with a colon -- ostrio:templatehelpers.js. Please rename and and re-publish the
package.                                                                                                                                               "

I'll add a pull request for this shortly

**Comment by dr-dimitru** [comment]
Hi @wildeyes thank you for submitting this issue. Fixed and published as [v1.1.2](https://github.com/VeliovGroup/Meteor-Template-helpers/releases/tag/1.1.2), [atmosphere](https://atmospherejs.com/ostrio/templatehelpers)

If you found this package useful, do not hesitate to star it at both [GitHub](https://github.com/VeliovGroup/Meteor-Template-helpers) and [Atmosphere](https://atmospherejs.com/ostrio/templatehelpers). Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Template-helpers&text=Meteorjs%2C%20do%20logic%20in%20your%20templates%20with%20ease!) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Template-helpers)
