### ISSUE TITLE
Compare always false

### ISSUE THREAD

**Issue by 2gen** [VeliovGroup/Meteor-Template-helpers#6]
Trying to use the compare helper and every time it will return false. Even using your examples:

{{log (compare 2 '>' 1)}}
{{log (compare 'one' '==' 'one')}}

Any idea?

**Comment by dr-dimitru** [comment]
Hello @2gen 

Returns `true` in both cases on my end.
Could we have minimal reproduction repo?

**Comment by dr-dimitru** [comment]
@2gen any news on your end? Have you managed to solve it?

**Comment by 2gen** [comment]
Forgot to update.

Yes, it was my error. There was a helper defined previously with the same name "compare" so the Meteor-Template-helpers "compare" wasn't being used. Removing the previously declared helper resolved the issue.

Thanks.
