### ISSUE TITLE
compare many to many always returns true.

### ISSUE THREAD

**Issue by distalx** [VeliovGroup/Meteor-Template-helpers#7]
compare many to many (**&&**)  always returns true.

```
{{compare 4 'gte' 1 '&&' 4 'lte' 6}}   // ture
{{compare 4 'gte' 7 '&&' 4 'lte' 8}}   // ture
{{compare 4 'gte' 9 '&&' 4 'lte' 10}}  // ture
```
  

  Version of `ostrio:templatehelpers` : **2.1.4**
  Version of `Meteor` : **1.6.1.1**
  Browser name : chrome
  Platform : mac

[Link](https://github.com/distalx/Meteor-Template-helpers-reproduction) to the reproduction repo.

**Comment by dr-dimitru** [comment]
@distalx thank you for the info, details, and reproduction repo.

This issue is fixed in [`v2.2.0` release](https://github.com/VeliovGroup/Meteor-Template-helpers/releases/tag/2.2.0).

**Comment by dr-dimitru** [comment]
@distalx let me know how it works on your end.

**Comment by distalx** [comment]
@dr-dimitru Thank you.  it is working fine now.
